name: Jekyll site CI
<meta name="google-site-verification" content="uF-yOQPIQCtlVp4Qrc92mZs7852iBpNKqHZzdXaTDug" />
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
<meta name="google-site-verification" content="uF-yOQPIQCtlVp4Qrc92mZs7852iBpNKqHZzdXaTDug" />
    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
